Repository dbm-network/mods, pull requests merged in 2020-05, with the labels that each got.

#331 Update Play Youtube
  actions/play_youtube.js
Labels: meta: cleanup, p: low, type: bugfix

#345 Allow usage of variables in canvas_image_options_MOD.js
  actions/canvas_image_options_MOD.js
Labels: meta: cleanup, type: enhancement

#342 Update store_server_info.js
  actions/store_server_info.js
Labels: t: utility, type: enhancement
