Repository dbm-network/mods, pull requests merged in 2020-07, with the labels that each got.

#397 Updated Create Embed Message and Edit Message
  actions/create_embed_message.js
  actions/edit_message.js
Labels: meta: cleanup

#401 docs: updated download links & how to install dbm alpha
  README.md
Labels: meta: documentation

#402 Added anchor options to conditionals
  actions/check_dbl_voted_MOD.js
  actions/check_global_data_MOD.js
  actions/check_if_command_exists_MOD.js
  actions/check_if_file_exists_MOD.js
  actions/check_if_member_MOD.js
  actions/check_if_message_MOD.js
  actions/check_if_user_reacted_MOD.js
  actions/check_member_data.js
  actions/check_parameters.js
  actions/check_permissions_MOD.js
  actions/check_role_permissions_MOD.js
  actions/check_server_data.js
  actions/check_variable.js
  actions/set_time_restriction_MOD.js
Labels: meta: refactor, t: utility

#403 Update anchor_jump_MOD.js
  actions/anchor_jump_MOD.js
Labels: t: utility, type: bugfix

#404 Update send_message.js
  actions/send_message.js
Labels: t: utility, type: bugfix

#405 Update send_message_to_console_MOD.js
  actions/send_message_to_console_MOD.js
Labels: type: bugfix

#407 Update Fix for anchor options
  actions/await_reaction_call_action_MOD.js
  actions/await_response_call_action_MOD.js
  actions/check_dbl_voted_MOD.js
  actions/check_if_command_exists_MOD.js
  actions/check_if_file_exists_MOD.js
  actions/check_if_member_MOD.js
  actions/check_if_message_MOD.js
  actions/check_member_data.js
  actions/check_parameters.js
  actions/check_role_permissions_MOD.js
  actions/check_server_data.js
  actions/set_channel_permissions.js
  actions/set_time_restriction_MOD.js
Labels: meta: cleanup, t: utility

#409 Create botsfordiscord_stats_MOD.js
  actions/botsfordiscord_stats_MOD.js
Labels: t: utility, type: enhancement

#410 Add anchor options
  actions/delete_bulk_messages_MOD.js
  actions/find_member.js
  actions/send_embed_message.js
  actions/send_mail_MOD.js
  actions/send_message.js
Labels: t: utility, type: enhancement

#413 Update ban_member.js
  actions/ban_member.js
Labels: meta: cleanup

#412 Update mod
  actions/set_time_restriction_MOD.js
  actions/store_data_list_MOD.js
Labels: meta: refactor, t: utility

#417 Update blacklist_MOD.js
  actions/blacklist_MOD.js
Labels: type: bugfix

#418 Update send_message_to_console_MOD.js
  actions/send_message_to_console_MOD.js
Labels: type: bugfix

#422 Update run_script.js
  actions/run_script.js
Labels: t: utility, type: enhancement

#425 v12 update
  actions/clone_channel_MOD.js
Labels: type: bugfix

#426 Update member_data_list_MOD.js
  actions/member_data_list_MOD.js
Labels: type: bugfix

#427 Update blacklist_MOD.js
  actions/blacklist_MOD.js
Labels: type: bugfix

#429 Update speed_test_MOD.js
  actions/speed_test_MOD.js
Labels: type: bugfix

#432 Make Restart Bot close old node process
  actions/restart_bot_MOD.js
Labels: p: low, t: utility, type: bugfix

#433 Update anchor_jump_MOD.js
  actions/anchor_jump_MOD.js
Labels: type: enhancement

#431 Refactored Download File
  actions/download_file_MOD.js
Labels: meta: refactor, p: medium, t: utility

#440 Update store_audit_log_list_MOD.js
  actions/store_audit_log_list_MOD.js
Labels: t: utility, type: bugfix

#441 Update master.json
  docs/master.json
Labels: meta: documentation

#443 Update mods.json
  docs/mods.json
Labels: meta: documentation

#444 Create run_command_in_console_MOD.js
  actions/run_command_in_console_MOD.js
  docs/mods.json
Labels: t: utility, type: enhancement

#448 Send Message to Twitch Chat action
  actions/send_message_to_twitch_chat_MOD.js
  docs/mods.json
Labels: t: utility, type: enhancement

#450 Adjusting cleverbot-MOD.js
  actions/cleverbot_MOD.js
Labels: t: utility, type: enhancement

#453 fix: Run SQL Query
  actions/run_sql_query_MOD.js
Labels: t: utility, type: bugfix

#454 Update play_youtube.js
  actions/play_youtube.js
Labels: meta: cleanup, t: utility

#455 Update run_sql_query_MOD.js
  actions/run_sql_query_MOD.js
Labels: p: medium, t: utility, type: bugfix

#457 Update run_sql_query_MOD.js
  actions/run_sql_query_MOD.js
Labels: t: utility, type: bugfix

#460 Fix Run SQL Query
  actions/run_sql_query_MOD.js
Labels: t: utility, type: bugfix

#464 Updated SQL query
  actions/run_sql_query_MOD.js
Labels: t: utility, type: bugfix

#465 Update set_time_restriction_MOD.js
  actions/set_time_restriction_MOD.js
Labels: meta: cleanup, t: utility

#466 fix: RegExp separator
  actions/store_message_params_MOD.js
Labels: t: utility, type: bugfix

#467 Update youtube_search_MOD.js
  actions/youtube_search_MOD.js
Labels: meta: refactor, t: utility

#468 replace youtube-info with ytsr to fix 403 error
  actions/youtube_info_MOD.js
Labels: meta: refactor, t: utility

#471 Fix error
  actions/youtube_info_MOD.js
Labels: t: utility, type: bugfix

#472 Thanks to leonz added bunch more options back
  actions/youtube_info_MOD.js
Labels: t: utility, type: enhancement

#475 Added NSFW options to Edit Channel
  actions/edit_channel_MOD.js
Labels: t: utility, type: enhancement

#476 Added "result" to Store In to avoid confusion
  actions/run_command_in_console_MOD.js
Labels: meta: documentation, t: utility

#477 Fix Delete Bulk Messages MOD and made Stop Bot exit node process
  actions/delete_bulk_messages_MOD.js
  actions/stop_bot_MOD.js
Labels: meta: refactor, t: utility, type: bugfix

#479 Added TTS Mod
  actions/text_to_speech_MOD.js
  docs/mods.json
Labels: t: voice, type: enhancement

#483 Convert to world time
  actions/convert_to_world_time_MOD.js
  docs/mods.json
Labels: t: utility, type: enhancement

#485 Replace simple-youtube-api with ytpl + eslint fix
  actions/play_youtube_playlist_MOD.js
Labels: meta: refactor, t: utility

#486 Store File Info
  actions/store_file_info_MOD.js
  docs/mods.json
Labels: t: utility, type: enhancement

#490 Added descriptions to all mods
  docs/mods.json
Labels: meta: documentation
