Repository dbm-network/mods, pull requests merged in 2020-06, with the labels that each got.

#358 Update edit_embed_object_MOD.js
  actions/edit_embed_object_MOD.js
Labels: meta: cleanup

#359 Update create_embed_message.js
  actions/create_embed_message.js
Labels: meta: cleanup

#356 Create ban_member.js
  converted/ban_member.js
Labels: type: enhancement

#354 Create ban_member.js
  actions/ban_member.js
Labels: type: enhancement

#361 Update edit_embed_object_MOD.js
  actions/edit_embed_object_MOD.js
Labels: meta: refactor

#362 Update edit_embed_object_MOD.js
  converted/edit_embed_object_MOD.js
Labels: meta: cleanup, meta: refactor

#363 Update create_embed_message.js
  default_actions/create_embed_message.js
Labels: meta: cleanup

#365 Update aaa_wrexmods_dependencies_MOD.js
  not_converted/aaa_wrexmods_dependencies_MOD.js
Labels: meta: cleanup, meta: refactor

#368 Update parse_from_stored_json_MOD.js
  actions/parse_from_stored_json_MOD.js
Labels: type: bugfix

#369 Updated and moved clone_channel_MOD.js
  actions/clone_channel_MOD.js
Labels: meta: cleanup

#370 Update aaa_dbmmods_dependencies_MOD.js
  actions/aaa_dbmmods_dependencies_MOD.js
Labels: semver: patch

#382 Add permissions mods
  actions/check_permissions_MOD.js
  actions/compare_permissions_MOD.js
  actions/control_permissons_MOD.js
  actions/create_permission_MOD.js
  actions/set_channel_permissions.js
  actions/set_permissions_MOD.js
  actions/store_channel_permissions_MOD.js
  actions/store_permissions_Info_MOD.js
  actions/sync_channel_permissions_MOD.js
Labels: t: utility, type: enhancement

#376 Update aaa_wrexmods_dependencies_MOD.js
  actions/aaa_wrexmods_dependencies_MOD.js
Labels: type: bugfix

#383 Updated, moved check_if_user_reacted.js
  actions/check_if_user_reacted_MOD.js
  not_converted/check_if_user_reacted_MOD.js
Labels: meta: cleanup

#385 moved and updated
  actions/check_role_permissions_MOD.js
Labels: type: enhancement

#384 Converted Store Message Params
  actions/store_message_params_MOD.js
Labels: meta: refactor, t: utility, type: enhancement

#390 Fetch reaction when returning
  actions/find_reaction_MOD.js
Labels: meta: cleanup, t: utility

#391 Fetch reaction
  actions/find_reaction_MOD.js
Labels: meta: refactor, semver: patch, t: utility

#388 moved + updated
  actions/set_member_voice_channel_perms_MOD.js
  actions/set_role_voice_channel_perms_MOD.js
  actions/set_voice_channel_permissions_MOD.js
Labels: meta: cleanup, type: bugfix

#392 Converted default actions
  default_actions/create_voice_channel.js
  default_actions/delete_emoji.js
  default_actions/find_channel.js
  default_actions/find_emoji.js
  default_actions/find_role.js
  default_actions/find_server.js
  default_actions/find_voice_channel.js
  default_actions/loop_through_all_servers.js
  default_actions/set_member_voice_channel.js
  default_actions/store_member_info.js
  default_actions/store_message_info.js
  default_actions/store_role_info.js
  default_actions/store_server_info.js
Labels: meta: refactor

#396 Moved + Fixed
  actions/edit_message.js
Labels: meta: cleanup

#394 Add some Data Control Features
  actions/check_global_data_MOD.js
  actions/control_global_data_MOD.js
  actions/delete_global_data_MOD.js
  actions/delete_member_data_MOD.js
  actions/delete_server_data_MOD.js
  actions/store_global_data_MOD.js
Labels: t: utility, type: enhancement
